version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: gunicorn todo_app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    depends_on:
      - db
    environment:
      - DEBUG=False
      - DATABASE_URL=postgres://todo_user:todo_password@db:5432/todo_db
    ports:
      - "8000:8000"

  redis:
    image: redis:latest

  celery:
    build: .
    command: celery -A todo_app worker -l info
    volumes:
      - .:/code
    depends_on:
      - redis
      - db

  beat:
    build: .
    command: celery -A todo_app beat -l info
    volumes:
      - .:/code
    depends_on:
      - redis
      - db

  flower:
    image: mher/flower:0.9.7
    command: ['flower', '--broker=redis://redis:6379', '--port=5555']
    ports:
      - 5557:5555
    depends_on:
      - redis

volumes:
  postgres_data:
