# Generated by Django 3.2 on 2024-07-15 20:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todotask",
            old_name="created_at",
            new_name="created",
        ),
        migrations.RenameField(
            model_name="todotask",
            old_name="modified_at",
            new_name="modified",
        ),
    ]
