# Generated by Django 3.2 on 2024-07-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20240716_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotask',
            name='remind_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
