# Generated by Django 3.2 on 2024-07-16 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0005_alter_todotask_remind_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todotask",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
